
// Generated by xt-genmpu.

#include <stdint.h>
#include <xtensa/hal.h>

#if defined (__cplusplus)
extern "C"
#endif
const struct xthal_MPU_entry
__xt_mpu_init_table[] __attribute__((section(".ResetHandler.text"))) = {
  XTHAL_MPU_ENTRY(0x00000000, 1, XTHAL_AR_NONE, XTHAL_MEM_DEVICE), // guard_zero
  XTHAL_MPU_ENTRY(0x20000000, 1, XTHAL_AR_R, XTHAL_MEM_NON_CACHEABLE | XTHAL_MEM_BUFFERABLE | XTHAL_MEM_SYSTEM_SHAREABLE), // L2_ram_arm
  XTHAL_MPU_ENTRY(0x20020000, 1, XTHAL_AR_RWX, XTHAL_MEM_WRITEBACK | XTHAL_MEM_NON_SHAREABLE), // L2_ram_fx
  XTHAL_MPU_ENTRY(0x20200000, 1, XTHAL_AR_RX, XTHAL_MEM_WRITEBACK_NOALLOC | XTHAL_MEM_NON_SHAREABLE), // L2_boot_code_0
  XTHAL_MPU_ENTRY(0x28240000, 1, XTHAL_AR_RW, XTHAL_MEM_NON_CACHEABLE | XTHAL_MEM_BUFFERABLE | XTHAL_MEM_SYSTEM_SHAREABLE), // L1_data_mp
  XTHAL_MPU_ENTRY(0x282c0000, 1, XTHAL_AR_RWX, XTHAL_MEM_NON_CACHEABLE | XTHAL_MEM_BUFFERABLE | XTHAL_MEM_SYSTEM_SHAREABLE), // L1_code_mp
  XTHAL_MPU_ENTRY(0x28a40000, 1, XTHAL_AR_NONE, XTHAL_MEM_NON_CACHEABLE | XTHAL_MEM_NON_SHAREABLE), // L2_boot_code_arm
  XTHAL_MPU_ENTRY(0x28a80000, 1, XTHAL_AR_NONE, XTHAL_MEM_NON_CACHEABLE | XTHAL_MEM_BUFFERABLE | XTHAL_MEM_SYSTEM_SHAREABLE), // L1_code_arm
  XTHAL_MPU_ENTRY(0x28ac0000, 1, XTHAL_AR_R, XTHAL_MEM_NON_CACHEABLE | XTHAL_MEM_BUFFERABLE | XTHAL_MEM_SYSTEM_SHAREABLE), // L1_data_arm
  XTHAL_MPU_ENTRY(0x2f780000, 1, XTHAL_AR_RW, XTHAL_MEM_NON_CACHEABLE | XTHAL_MEM_BUFFERABLE | XTHAL_MEM_NON_SHAREABLE), // L1_data
  XTHAL_MPU_ENTRY(0x2f800000, 1, XTHAL_AR_RWX, XTHAL_MEM_NON_CACHEABLE | XTHAL_MEM_BUFFERABLE | XTHAL_MEM_NON_SHAREABLE), // L1_code
  XTHAL_MPU_ENTRY(0x30000000, 1, XTHAL_AR_RW, XTHAL_MEM_DEVICE), // System_mmr
  XTHAL_MPU_ENTRY(0x60000000, 1, XTHAL_AR_RWX, XTHAL_MEM_WRITETHRU_WRITEALLOC | XTHAL_MEM_NON_SHAREABLE), // SPI_data
  XTHAL_MPU_ENTRY(0x80000000, 1, XTHAL_AR_RWX, XTHAL_MEM_WRITEBACK | XTHAL_MEM_NON_SHAREABLE), // L3_ram_fx
  XTHAL_MPU_ENTRY(0x90000000, 1, XTHAL_AR_R, XTHAL_MEM_NON_CACHEABLE | XTHAL_MEM_BUFFERABLE | XTHAL_MEM_SYSTEM_SHAREABLE), // L3_ram_arm
};

#if defined (__cplusplus)
extern "C"
#endif
const uint32_t __xt_mpu_init_table_size __attribute__((section(".ResetHandler.text"))) = 15;

#if defined (__cplusplus)
extern "C"
#endif
const uint8_t __xt_mpu_init_cacheadrdis __attribute__((section(".ResetHandler.text"))) = 0xe5;

#if defined (__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)
#include <assert.h>
static_assert(sizeof(__xt_mpu_init_table)/sizeof(__xt_mpu_init_table[0]) == 15, "Incorrect MPU table size");
#endif
